management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
    metrics:
      enabled: true
    prometheus:
      enabled: true
    export:
      prometheus:
        enabled: true